### ISSUE TITLE
Trademark link not recognized

### ISSUE THREAD

**Issue by chalin** [cncf/clomonitor#1326]
I recently added to the [OTel website](https://opentelemetry.io/) a link to the LF trademark page. If I used the [first regex from the CLOmonitor docs](https://clomonitor.io/docs/topics/checks/#legal), I get a match:

```console
$ curl -s https://opentelemetry.io | perl -ne 'print if /https:\/\/(?:www\.)?linuxfoundation\.org\/(?:legal\/)?trademark-usage/' | wc -l
       1
```

But legal is still marked as unmatched, see https://clomonitor.io/projects/cncf/open-telemetry#community_legal:

> <img width="954" alt="image" src="https://github.com/cncf/clomonitor/assets/4140793/cbf33cac-b290-4ebd-bf1c-22e46650584e">

What am I missing? Thanks!

/cc @svrnm @nate-double-u

**Comment by tegioz** [comment]
Hi @chalin 👋

The CLOMonitor tracker runs every hour and processes a repository when:

- It has changed since the last time it was processed (i.e. new commit on the repo)
- Or it's been a day since the last time it was processed

In this case, the OTel community repo last change was 2 days ago, which means it'll be processed once a day until it changes again. The last time it was processed was `2023-10-18 15:01:07.377759+00`, but you committed the trademark change shortly after (24 mins), at `Wed Oct 18 11:25:22 2023 -0400` (plus the time it took to deploy it). So by the time the repository was processed, the trademark wasn't there yet.

If this is correct it should be fixed automatically in less than 5 hours (unless something is committed to the community repository before) 😇

**Comment by chalin** [comment]
That makes sense, but what confused me was the "timestamp" at the top of the page. For example, as I write this it reads "Updated 2 hours ago":

> <img width="645" alt="image" src="https://github.com/cncf/clomonitor/assets/4140793/74b6279f-73ca-46d4-896d-61d30f132d13">

This is confusing, because if the tool fully processed all OTel repos (and hence the website too) 2 hours ago, then the legal status should have been updated.

**Comment by chalin** [comment]
Btw, would it be possible to add a `title` to the "Updated" text so that it shows the actual timestamp (similarly to what GitHub does)?

**Comment by tegioz** [comment]
> That makes sense, but what confused me was the "timestamp" at the top of the page. For example, as I write this it reads "Updated 2 hours ago":

Yes, I understand. That timestamp is updated every time the project score is updated, which happens when any of the repositories is updated. Maybe we can add an information icon that explains this a bit in a popover.

**Comment by tegioz** [comment]
> Btw, would it be possible to add a `title` to the "Updated" text so that it shows the actual timestamp (similarly to what GitHub does)?

We could do that, yes.

**Comment by tegioz** [comment]
We could also display this information per repository as well.

**Comment by chalin** [comment]
Since the scores depend on website, wouldn't it make sense to check whether the website has changed? A good candidate file to check would be the sitemap. WDYT?

**Comment by tegioz** [comment]
> If this is correct it should be fixed automatically in less than 5 hours (unless something is committed to the community repository before) 😇

The check passed on the next run, all good now 🙂

**Comment by chalin** [comment]
Ok, what ever solution you think is most appropriate. As long as we can resolve the ambiguity / placebo effect of the current page-wide timestamp.

> Maybe we can add an information icon that explains this a bit in a popover.

Yes, that sounds helpful.
