### ISSUE TITLE
Increase .clomonitor.yml configuration

### ISSUE THREAD

**Issue by jeefy** [cncf/clomonitor#140]
Feel free to close this and break it up into separate issues, but I want to capture all the ideas under one since they all involve .clomonitor.yml :) 

- [x] We should be able to specify alternative locations for some checks
    For example, https://github.com/project-akri/akri has the header `Community, Contributing, and Support`, which also links to their Contributing page https://docs.akri.sh/community/contributing. 
    Being able to specify in the YAML something like `contributing_url: https://docs.akri.sh/community/contributing` and pass the check would be great
- [ ] We should be able to skip/pass certain checks in `.clomonitor.yml`. For example(s), Akri or Envoy explicitly state on their docs that they're part of the CNCF. This is technically an accepted path (See https://github.com/cncf/toc/issues/719#issuecomment-984761019)

**Comment by tegioz** [comment]
Hi @jeefy 

>  We should be able to specify alternative locations for some checks
>   For example, https://github.com/project-akri/akri has the header `Community, Contributing, and Support`, which also links to their Contributing page https://docs.akri.sh/community/contributing.
>   Being able to specify in the YAML something like `contributing_url: https://docs.akri.sh/community/contributing` and pass the check would be great

A user [brought this up recently](https://github.com/cncf/clomonitor/issues/120#issue-1158314086) and we mentioned [we were considering making it configurable](https://github.com/cncf/clomonitor/issues/120#issuecomment-1057973797)  via `.clomonitor.yml`.

However, we're not really sure if this the right thing to do, specially for documentation related checks. The reason is that IMHO it'd be great if we could encourage projects to make this information a bit easier to discover by final users. Having this information in `.clomonitor.yml` would make it much easier for us to check, but probably wouldn't help users.

So in addition to support some standard well known locations, some checks are now able to detect certain headers in README files (checks like `adopters`, `governance`, `changelog`, `roadmap`, etc). This way projects can have this information at their preferred location and users have a better chance of finding it when going through the README file. The [Kubernetes](https://github.com/kubernetes/kubernetes/pull/108110) and [Cilium](https://github.com/cilium/cilium/pull/19037) projects are making CLOMonitor happy this way 🙂 

The `Contributing` check does not support headers in the README file yet, but we'll take care of it tomorrow 😉

**Comment by tegioz** [comment]
> The `Contributing` check does not support headers in the README file yet, but we'll take care of it tomorrow 😉

Done, Akri's contributing check is now passing.

**Comment by jeefy** [comment]
Could we perhaps pass the `Trademark` check if there's an additional Header in the README.md or a TRADEMARK.md exists in the docs (that contains what we're expecting)? 

I think that'll give enough flexibility and control to close this out. I'm happy to close this issue and create a new one for this if that's easier. :)

**Comment by tegioz** [comment]
> Could we perhaps pass the `Trademark` check if there's an additional Header in the README.md or a TRADEMARK.md exists in the docs (that contains what we're expecting)?

Sure, this is not a problem. However, I thought this was a requirement as mentioned in the [website guidelines document](https://github.com/cncf/foundation/blob/main/website-guidelines.md):

> 7. Website footers must include trademark guidelines by either linking to [Trademark Usage](https://www.linuxfoundation.org/trademark-usage/) (directly or via a "Terms of service" page), or by including the following text: "The Linux Foundation® (TLF) has registered trademarks and uses trademarks. For a list of TLF trademarks, see [Trademark Usage](https://www.linuxfoundation.org/trademark-usage/)".

@caniszczyk requested this one in #73, maybe he can confirm 🙂

**Comment by jeefy** [comment]
That's super helpful! Thanks!

**Comment by tegioz** [comment]
I think we can close this one now, please feel free to reopen if needed.
