### ISSUE TITLE
Improve Website check

### ISSUE THREAD

**Issue by jeefy** [cncf/clomonitor#155]
Some projects have their website set at the Org level and not the individual project-level. 

This is a valid option and should pass the check.

Example: 
https://clomonitor.io/projects/chubao-fs/chubao-fs - Failed website check
https://github.com/cubeFS/cubefs - No site specified here
https://github.com/cubeFS - Site is specified here

Edit: That said, I do want to push projects that have (essentially) a primary repo to also have their website linked. But there are some projects that are relatively large in repo-size, so org-level-linking should be valid.

**Comment by tegioz** [comment]
Hi @jeefy 

I've just created a PR (#184) to extend this check. However, IMHO I'm not sure if we'd be helping final users by merging it.

At the moment, when a user lands on that repo, they can't easily find a website to visit. They could find it by other means, indeed, but we should probably aim for better.

I think we should strive to encourage projects to make this kind of information easier to discover, specially on the main project's repository. In this case it's something that can be easily fixed by adding a website to the repo, which would benefit users and get that check passed.

Happy to merge or discard the PR, up to you 🙂

*BTW: the website link in the org <https://chubao.io> does not work fine (the certificate is not covering the non-www variant). <https://www.chubao.io> does work though.*

**Comment by jeefy** [comment]
The more I think about it, the stronger I agree with this point: 
> I think we should strive to encourage projects to make this kind of information easier to discover, specially on the main project's repository

The biggest road block to that is, projects that may not have a "main repo". I think we might start nudging projects to all have a "community" or governance-style repo that could be cover this. (Going back to #151) 

Given that, the PR should probably be discarded. Appreciate the PR and continuing to talk through all this! <3

**Comment by tegioz** [comment]
Thanks @jeefy! ❤️
