### ISSUE TITLE
Add "recheck" button

### ISSUE THREAD

**Issue by chalin** [cncf/clomonitor#185]
Kind of a followup to #176. Might it be possible to add a "recheck" button to a project's Clomonitor page? /cc @nate-double-u

**Comment by tegioz** [comment]
Hi @chalin 👋 

It would be possible but we'd rather not add it, at least for now. One of the reasons is that some checks rely on the Github APIs, which are rate limited. So if this feature was misused or abused it could have a negative impact on the service.

At the moment repositories are checked every *hour* provided they have changed since the last check, so in the worst case after one hour an up-to-date report should be available. I'd say this sounds reasonable, but we could consider checking more often if this is a problem though.

One interesting usage of this button could be to verify if clomonitor is happier with a given project after some changes are applied on one of its repos. However, I think this can be handled better by running the clomonitor linter locally (please see screenshot below) or from CI workflows (you can find an example of how to integrate it with Github Actions [in the Artifact Hub repository](https://github.com/artifacthub/hub/blob/773d8e82d2f4153ee93aafd78f3ff97e071f3829/.github/workflows/ci.yml#L40-L49)). This way changes in repos can be checked even before they are committed.

### `clomonitor-linter` running locally

<img width="1439" alt="linter-cli" src="https://user-images.githubusercontent.com/1213902/158782105-bc29a001-071a-465a-9756-f98f37a95477.png">

We provide a [Docker image](https://gallery.ecr.aws/clomonitor/linter) that contains this tool and we'd like to also provide binaries for multiple platforms soon 🙂.

Hope this helps.-

**Comment by chalin** [comment]
Yes, thanks @tegioz.
