### ISSUE TITLE
gRPC repo list needs to be adjusted

### ISSUE THREAD

**Issue by chalin** [cncf/clomonitor#217]
This is the current repo list for [gRPC]:

> <img width="380" alt="image" src="https://user-images.githubusercontent.com/4140793/161403296-7250ed31-5310-463c-abb2-4c51b1a64894.png">

How is this list determined?

The following changes should be made, among others:

- Add doc/website repo: https://github.com/grpc/grpc.io
- Add community: https://github.com/grpc/grpc-community
- The main repo is mislabeled as `code + community` IMHO, it should be only `code`

/cc @ejona86 @grpc/grpc-docs-team (team links don't seem to work :( )

**Comment by tegioz** [comment]
Hi @chalin 👋 

> How is this list determined?

Most of the time from the organization's pinned repositories, but sometimes we add some extra ones like community repos.

> The following changes should be made, among others:
> * Add community: https://github.com/grpc/grpc-community
> * The main repo is mislabeled as `code + community` IMHO, it should be only `code`

Please note that the label `code + community` in CLOMonitor defines the [checks sets](https://github.com/cncf/clomonitor/blob/main/docs/checks.md) we run on the repo, not the kind of repo. At the moment, we've added only one repo for the majority of projects listed in CLOMonitor, and we run both the code and community checks on it.

In this case the main repo is passing more community checks that the community repo itself. That's why we didn't include it and assigned both check sets to the main repo. We are happy to make these changes, just wanted to double check with you as fewer checks will pass and the score will be worse.

## Community checks run in `grpc` repo

<img width="1066" alt="grpc" src="https://user-images.githubusercontent.com/1213902/161487401-a9b3a09c-59a2-4a46-bca5-aed7291638b1.png">

## Community checks run in `grpc-community` repo

<img width="1204" alt="grpc-community" src="https://user-images.githubusercontent.com/1213902/161487409-f801ea35-59d3-4a5a-98b7-78bed4121ece.png">

**Comment by tegioz** [comment]
Related to #216

**Comment by tegioz** [comment]
The grpc.io docs repository has been added.

Will close this issue for now, please feel free to reopen it if needed.
