### ISSUE TITLE
Ability to see check outputs

### ISSUE THREAD

**Issue by duglin** [cncf/clomonitor#253]
Is there a way to make the results of the check visible to us? For example, for https://github.com/cncf/clomonitor/blob/main/docs/checks.md#recent-release I'm looking at the results for CloudEvents python sdk: https://clomonitor.io/projects/cncf/cloudevents/cloudevents#sdk-python_best_practices and it claims there isn't a recent release. But I created one for it about 2 hours ago. Maybe I just need to wait a little longer, but it got me wondering if it would be possible for me to see the output from the check to see why it failed - then it might make debugging easier for folks and they won't need to ping you guys :-)

**Comment by tegioz** [comment]
Hi @duglin 👋 

When something goes wrong during a check, the error is already displayed on the UI. However, when the check just cannot find what it is looking for, nothing is displayed.

<img width="855" alt="check-error" src="https://user-images.githubusercontent.com/1213902/165462256-9396cbbc-9c2c-4d1d-90f5-76b95090588e.png">

In this case, the reason why the check isn't passing is the release creation date. The release you created yesterday, according to the Github API, has a creation date of `2020-08-11`, which is probably taken from the tag it points to (`1.0.0`). The publish date, however, is set to `2022-04-26` as expected. The CLOMonitor check relies at the moment on the `created_at` field, so the release is considered to be older than 1 year old and the check does not pass.

We could change how this works and use the publish date instead, but I'm not sure if we'd be doing the right thing. In the end, even though the release was created yesterday, its content is almost 2 years old. There have been some changes in the repo since then, so maybe you could add a new tag and create a new release pointing to it.

Please note that repositories are checked every hour provided something has changed since the last time we checked. We rely on the last commit sha to check if something has changed. So if you create a new release but nothing is committed to the repo after that, you may have to wait a bit for the report to be updated until the daily check kicks in (24 hours since the last change).

**Comment by duglin** [comment]
Thanks for the response. Is there a way to disable that check for a repo? I’m not sure it makes sense in all cases for a project to now be questionable just because everything is ok with the code and a new release isn’t needed.

**Comment by duglin** [comment]
Otherwise games might be played and pointless releases will be created just to satisfy the tool. Which would seem to go against the point here.

**Comment by tegioz** [comment]
No worries!

Yes, there is, please see [the exemptions section](https://github.com/cncf/clomonitor/blob/main/docs/checks.md#exemptions) in the checks documentation. The check will be specially marked in the UI and the reason you provide that justifies the exemption displayed.

However, I'd strongly recommend to not use it for this particular check. The CloudEvents projects has a superb score of 99, almost perfect, and definitely won't be questionable for not passing a single check in one of the repos 🙂 But IMHO adding an exemption for it would make it look worse than not passing the check, as it may look suspicious. Most projects will probably need to produce a release every now and then, even if it's just to update some dependencies with potential vulnerabilities or fix minor bugs.

**Comment by tegioz** [comment]
This is how an exemption looks like in the UI. It's a good example as [Cilium was approved to keep their Slack separate from the CNCF or K8s Slack](https://github.com/cncf/clomonitor/issues/120#issuecomment-1072436814), so the exemption is well justified.

<img width="877" alt="exemption" src="https://user-images.githubusercontent.com/1213902/165513926-76988476-eb3b-4fcd-af2e-76c80fa82677.png">

**Comment by duglin** [comment]
I guess it depends on what the CLO is supposed to check for... best practices or "active project". I kind of assumed it was more about best practices and not to make a judgement call about that status of a project.... which is very subjective, and for a mature/stable project could actually be misleading/wrong.

**Comment by duglin** [comment]
I added this: https://github.com/cloudevents/sdk-python/blob/master/.clomonitor.yaml 
to test the exemption process but it doesn't look like it worked. I don't see any errors on the CloudEvents CLO page - did I have a typo in there?

**Comment by tegioz** [comment]
Yes, small typo: the metadata file must be `.clomonitor.yml`.

**Comment by duglin** [comment]
Ah - thanks. It's happy now.
