### ISSUE TITLE
DCO check should be passing

### ISSUE THREAD

**Issue by xmulligan** [cncf/clomonitor#259]
For the Cilium project, we use DCO https://docs.cilium.io/en/v1.11/contributing/development/contributing_guide/#dev-coo. We even have a bot that checks each commit for sign off https://github.com/cilium/cilium/pull/19562#issuecomment-1108703593.

However the DCO check in CLOmonitor is currently failing. I read through the docs and I don't quite understand what it is checking for. Can you let me know what we are missing?

**Comment by tegioz** [comment]
Hi @xmulligan 👋 

At the moment we are looking for a check named `dco` in the last closed PR. There are a few ways that check can end up on the list below, like using the DCO Github app, for example.

<img width="813" alt="dco" src="https://user-images.githubusercontent.com/1213902/165733516-dd4cab3e-7bd8-43d3-9cbb-340db18db6af.png">

In your case your are enforcing DCO by using a bot (`maintainer-s-little-helper`) that the check is not aware of, that's why it's not passing.

This check used to have a mechanism to verify that the last X commits in the repo had been signed off, but we disabled it a few weeks ago as it was rarely useful and it was slowing some things down. But I think we'll enable it back for now, which should fix this issue. Leave it with us, we'll keep you posted 🙂

**Comment by tegioz** [comment]
It's done, we'll deploy it later today!

**Comment by xmulligan** [comment]
Thanks for the help resolving the issue!
