### ISSUE TITLE
Ensure that .csv files are actually CSV files

### ISSUE THREAD

**Issue by chalin** [cncf/clomonitor#508]
GitHub has a web interface for viewing and editing of data files, including CSV. For details, see https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files#rendering-csv-and-tsv-data. Here's s screenshot of the GH i/f from the GH docs:

> ![image](https://user-images.githubusercontent.com/4140793/184038582-a911e182-d446-496c-a6b7-a53ca0bd5869.png)

It would be nice if the CLOmonitor data files, like those under https://github.com/cncf/clomonitor/tree/main/database/data/cncf, were actually formatted per the file suffix. Would that be possible?

I haven't actually tried the GH interface for editing tables, but it does seem more convenient than editing the raw text. Just a thought. Thanks!

/cc @nate-double-u @caniszczyk

**Comment by chalin** [comment]
Or maybe you have another suggestion for updating the data tables?

**Comment by tegioz** [comment]
Hi @chalin

We use semicolons in those data files instead of commas as separator because there are some fields (like checks sets or descriptions) that use commas very often. Those could be quoted though, but it can be error prone (i.e. some are missed).

Most spreadsheet software (Excel, Numbers, etc) should allow you to edit those files nicely, like in the screenshot you attached. Although they are not CSV strictly speaking, it's very common to name them this way as well when using some alternative common separators, and software that allows editing CSV files usually works fine with them (not GitHub yet though ;).

Said this, if you still think this can be a problem, we can change them 🙂 When adding new projects, it'll often be needed to edit multiple files (to add the org, project and repo, for example), not just one, so it'll probably be easier to do that on your local computer than from the GitHub UI anyway.

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
