### ISSUE TITLE
Add envoy-website as a repo for Envoy

### ISSUE THREAD

**Issue by chalin** [cncf/clomonitor#615]
Add https://github.com/envoyproxy/envoy-website as a repo for Envoy (https://clomonitor.io/projects/cncf/envoy). I'd have submitted a PR myself (based on, say #509), but it seems that things have changed since then, so I'll just create an issue for now.

**Comment by tegioz** [comment]
Hi @chalin 👋 

Adding a project or a repo should be easier now, you just need to add it to the [corresponding data file](https://github.com/cncf/clomonitor/tree/main/data) and CLOMonitor will pick it up automatically. So if you still would like to submit the PR, please go ahead. It'll be helpful to see how more people interact with the data files and how do they feel about it (if they encounter any problems, etc). Otherwise we are happy to do it, not a problem 🙂
