### ISSUE TITLE
Produce metrics over time / Reporting ideas

### ISSUE THREAD

**Issue by jeefy** [cncf/clomonitor#80]
I'm a huge supporter of providing metrics that we can scrape and do reporting on. To that end, I think a basic Prometheus metrics endpoint that publishes the CLO monitor data could be useful. 

With that, we could then: 
- create reports showing project trajectory over time (And hide projects that have hit some threshold)
- create "alerts" if projects slip or have a negative trajectory
- create "alerts" if a project has not improved their grade over a reasonable amount of time

Theoretically these numbers won't move often, but with every additional project we have more numbers to track.

**Comment by tegioz** [comment]
Related to #48

**Comment by tegioz** [comment]
Hi @jeefy 👋 

We have plans to expose some metrics to Prometheus, mostly API requests (duration, status, etc) and some other operational aspects of the service, to have some telemetry and debug potential issues. But we'll try to use PostgreSQL as the main and only datastore to power features until we hit something that cannot be easily done otherwise.

Alerts sound great, I really like it. We'd need to discuss when to alert, how (we've though about maybe creating issues automatically in the affected repos), who would receive them, etc. But maybe this can happen later when the set of checks is more stable and has been validated with more feedback 🙂 

Thanks!

**Comment by tegioz** [comment]
I think that we can close this one now that we have the [stats page](https://clomonitor.io/stats). It'd be great if you could open a dedicated issue for the alerts idea @jeefy to keep track of it 🙂 Thanks!
