### ISSUE TITLE
Any way to surface "time since last merge"

### ISSUE THREAD

**Issue by Salkimmich** [cncf/clomonitor#947]
I would love to be able to have a status for projects that are truly actively maintained and  see that represented some way on CLOmonitor. Specifically, I'd love to be able to see a stat for "time since last merged commit". 

1) Does this sound interesting enough to add in? 
2) If this could be in scope, is there another metric that would be easier to scrape to represent "staleness"?

Thank you!!

**Comment by tegioz** [comment]
Hi @Salkimmich 👋 

We already have a couple of related checks that might help with this 🙂

## Maintained check (security section)

This check comes from Scorecard and it indicates if the project is actively maintained. This check's score is based on the number of commits and issues activity on the repository during the last 90 days. The computed score varies based on that activity. You can see those details in CLOMonitor by hovering on the check's icon:

<img width="1225" alt="maintained" src="https://user-images.githubusercontent.com/1213902/221276249-483ef2ae-db9d-483d-a536-b945eaf5706e.png">

I think this kind of covers what you were describing (*projects that are truly actively maintained*), but if we can think of any improvements maybe we could propose them upstream so that more users can benefit of it.

## Recent release (best practices section)

We also have a check that verifies if the project has produced a release during the last year, which can be helpful as a complement to the maintained one (although the time span would be longer). The latest release found is linked to the check's title in CLOMonitor.

**Comment by tegioz** [comment]
No worries!

> What I'm curious most about is any clear predictive behaviour in the year before it becomes 'inactive'.

CLOMonitor stores projects' snapshots periodically, which can be viewed from the UI by using the timeline on the right side of each project page. When using this feature in combination with the `maintained` check's score I mentioned in my previous comment, it should be possible to identify a descending trend that could signal that risk of going stale. All this information is accessible from the CLOMonitor's API (which isn't documented yet 😅), just in case you need to do something programmatically with it 🙂

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
